import { StyleSheet } from 'react-native';

const TransactionStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "white",
        flexDirection: "column",
    },
    mainBody: {
        flexDirection: "column",
        backgroundColor: "powderblue",
        height: "75%",
        width: '100%',
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 5,
        borderColor: "teal",
        borderTopWidth: 0,
    },
    background: {
      flexDirection: "column",
      height: "100%",
      width: '100%',
      justifyContent: "center",
      alignItems: "center",
    },
    content: {
        //borderWidth: 5,
        //borderColor: "yellow",
        height: "80%",
        width: '80%',
        justifyContent: "center",
        alignItems: "center",
    },
    qrContainer: {
       // borderWidth: 5,
        //borderColor: "red",
        height: "50%",
        width: '80%',
        justifyContent: "center",
        alignItems: "center",
    },
    space1: {
      height: "15%",
      width: '100%',
      //borderWidth: 5,
      //borderColor: "red",
      padding: 5,
    },
    amountBox: {
      backgroundColor: "cadetblue",
      justifyContent: "center",
      alignItems: "center",
      height: "18%",
      width: '100%',
      borderWidth: 5,
      borderColor: "teal",
      borderTopLeftRadius: 15,
      borderTopRightRadius: 15,
      borderBottomLeftRadius: 15,
      borderBottomRightRadius: 15,
    },
    text: {
      textAlign: "center",
      fontSize: 30,
      fontWeight: "bold",
      color: "midnightblue",
      padding: 15,
      //borderWidth: 5,
      //borderColor: "yellow",
    },
    space2: {
      height: "5%",
      width: '100%',
      //borderWidth: 5,
      //borderColor: "red",
      padding: 15,
    },
    textConfirm: {
        textAlign: "center",
        fontSize: 25,
        fontWeight: "bold",
        color: "midnightblue",
        //borderWidth: 5,
        //borderColor: "yellow",
    },
    companyEntry: {
        alignSelf: "center",
        backgroundColor: "white",
        height: "20%",
        width: '50%',
        borderWidth: 3,
        borderColor: "teal",
        padding: 15,
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,   
    },
    buttonBox: {
      backgroundColor: "aliceblue",
      justifyContent: "center",
      alignItems: "center",
      height: "15%",
      width: '40%',
      borderWidth: 5,
      borderColor: "teal",
      borderTopLeftRadius: 40,
      borderTopRightRadius: 40,
      borderBottomLeftRadius: 40,
      borderBottomRightRadius: 40,
    },
  });

  export default TransactionStyles;
  